-- ============================================================
-- PRY2204 Experiencia 3 Semana 8 - Taller Mecanico Mikes Ltda.
-- Ejecutar conectado como PRY2204_S8 en FREEPDB1
-- ============================================================

-- === Drops manuales ===

DROP TABLE detalle_servicio CASCADE CONSTRAINTS PURGE;
DROP TABLE mantencion CASCADE CONSTRAINTS PURGE;
DROP TABLE automovil CASCADE CONSTRAINTS PURGE;
DROP TABLE cliente CASCADE CONSTRAINTS PURGE;
DROP TABLE servicio CASCADE CONSTRAINTS PURGE;
DROP TABLE mecanico CASCADE CONSTRAINTS PURGE;
DROP TABLE sucursal CASCADE CONSTRAINTS PURGE;
DROP TABLE ciudad CASCADE CONSTRAINTS PURGE;
DROP TABLE pais CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE seq_servicio;
DROP SEQUENCE seq_ciudad;

-- === Creacion de tablas ===

CREATE TABLE pais (
  id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 9 INCREMENT BY 3,
  nom_pais VARCHAR2(50) NOT NULL
);

CREATE TABLE ciudad (
  id_ciudad NUMBER NOT NULL,
  nom_ciudad VARCHAR2(50) NOT NULL,
  cod_pais NUMBER NOT NULL
);

CREATE TABLE sucursal (
  id_sucursal VARCHAR2(3) NOT NULL,
  nom_sucursal VARCHAR2(50) NOT NULL,
  calle VARCHAR2(80) NOT NULL,
  num_calle NUMBER NOT NULL,
  cod_ciudad NUMBER NOT NULL
);

CREATE TABLE mecanico (
  cod_mecanico NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 460 INCREMENT BY 7,
  pnombre VARCHAR2(40) NOT NULL,
  snombre VARCHAR2(40),
  apaterno VARCHAR2(40) NOT NULL,
  amaterno VARCHAR2(40),
  bono_jefatura NUMBER,
  sueldo NUMBER NOT NULL,
  monto_impuestos NUMBER NOT NULL,
  cod_supervisor NUMBER
);

CREATE TABLE cliente (
  rut_cliente NUMBER NOT NULL,
  dv VARCHAR2(1) NOT NULL,
  pnombre VARCHAR2(40) NOT NULL,
  snombre VARCHAR2(40),
  apaterno VARCHAR2(40) NOT NULL,
  amaterno VARCHAR2(40),
  email VARCHAR2(100),
  tipo_cliente VARCHAR2(20) NOT NULL
);

CREATE TABLE automovil (
  patente_auto VARCHAR2(10) NOT NULL,
  marca VARCHAR2(40) NOT NULL,
  modelo VARCHAR2(40) NOT NULL,
  anio NUMBER,
  rut_cliente NUMBER NOT NULL
);

CREATE TABLE servicio (
  id_servicio NUMBER NOT NULL,
  descripcion VARCHAR2(80) NOT NULL,
  costo NUMBER NOT NULL
);

CREATE TABLE mantencion (
  num_mantencion NUMBER NOT NULL,
  cod_sucursal VARCHAR2(3) NOT NULL,
  fecha_ingreso DATE NOT NULL,
  fecha_salida DATE,
  patente_auto VARCHAR2(10),
  cod_mecanico NUMBER NOT NULL,
  estado VARCHAR2(20) NOT NULL,
  costo_total NUMBER
);

CREATE TABLE detalle_servicio (
  num_detalle NUMBER NOT NULL,
  num_mantencion NUMBER NOT NULL,
  cod_sucursal VARCHAR2(3) NOT NULL,
  id_servicio NUMBER NOT NULL
);

-- === Restricciones iniciales ===

ALTER TABLE pais ADD CONSTRAINT pk_pais PRIMARY KEY (id_pais);
ALTER TABLE ciudad ADD CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad);
ALTER TABLE sucursal ADD CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal);
ALTER TABLE mecanico ADD CONSTRAINT pk_mecanico PRIMARY KEY (cod_mecanico);
ALTER TABLE cliente ADD CONSTRAINT pk_cliente PRIMARY KEY (rut_cliente);
ALTER TABLE automovil ADD CONSTRAINT pk_automovil PRIMARY KEY (patente_auto);
ALTER TABLE servicio ADD CONSTRAINT pk_servicio PRIMARY KEY (id_servicio);
ALTER TABLE mantencion ADD CONSTRAINT pk_mantencion PRIMARY KEY (num_mantencion);
ALTER TABLE detalle_servicio ADD CONSTRAINT pk_detalle_servicio PRIMARY KEY (num_detalle);

ALTER TABLE ciudad ADD CONSTRAINT fk_ciudad_pais
FOREIGN KEY (cod_pais) REFERENCES pais (id_pais);

ALTER TABLE sucursal ADD CONSTRAINT fk_sucursal_ciudad
FOREIGN KEY (cod_ciudad) REFERENCES ciudad (id_ciudad);

ALTER TABLE mecanico ADD CONSTRAINT fk_mecanico_supervisor
FOREIGN KEY (cod_supervisor) REFERENCES mecanico (cod_mecanico);

ALTER TABLE automovil ADD CONSTRAINT fk_automovil_cliente
FOREIGN KEY (rut_cliente) REFERENCES cliente (rut_cliente);

ALTER TABLE mantencion ADD CONSTRAINT fk_mantencion_sucursal
FOREIGN KEY (cod_sucursal) REFERENCES sucursal (id_sucursal);

ALTER TABLE mantencion ADD CONSTRAINT fk_mantencion_auto
FOREIGN KEY (patente_auto) REFERENCES automovil (patente_auto);

ALTER TABLE mantencion ADD CONSTRAINT fk_mantencion_mecanico
FOREIGN KEY (cod_mecanico) REFERENCES mecanico (cod_mecanico);

ALTER TABLE detalle_servicio ADD CONSTRAINT fk_detalle_mantencion
FOREIGN KEY (num_mantencion) REFERENCES mantencion (num_mantencion);

ALTER TABLE detalle_servicio ADD CONSTRAINT fk_detalle_servicio
FOREIGN KEY (id_servicio) REFERENCES servicio (id_servicio);

-- === Caso 2: modificaciones del modelo ===

ALTER TABLE mantencion DROP COLUMN costo_total;

ALTER TABLE detalle_servicio DROP CONSTRAINT fk_detalle_mantencion;
ALTER TABLE mantencion DROP CONSTRAINT pk_mantencion;

ALTER TABLE mantencion ADD CONSTRAINT pk_mantencion
PRIMARY KEY (num_mantencion, cod_sucursal);

ALTER TABLE detalle_servicio ADD CONSTRAINT fk_detalle_mantencion
FOREIGN KEY (num_mantencion, cod_sucursal)
REFERENCES mantencion (num_mantencion, cod_sucursal);

ALTER TABLE cliente ADD CONSTRAINT un_cliente_email UNIQUE (email);
ALTER TABLE cliente ADD CONSTRAINT ck_cliente_dv CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));
ALTER TABLE mecanico ADD CONSTRAINT ck_mecanico_sueldo CHECK (sueldo >= 510000);
ALTER TABLE mantencion ADD CONSTRAINT ck_mantencion_estado CHECK (estado IN ('Reserva','Ingresado','Entregado','Anulado'));

-- === Secuencias solicitadas ===

CREATE SEQUENCE seq_servicio START WITH 400 INCREMENT BY 2;
CREATE SEQUENCE seq_ciudad START WITH 165 INCREMENT BY 5;

-- === Poblamiento de datos ===

INSERT INTO pais (id_pais, nom_pais) VALUES (9, 'Chile');
INSERT INTO pais (id_pais, nom_pais) VALUES (12, 'Peru');
INSERT INTO pais (id_pais, nom_pais) VALUES (15, 'Colombia');

INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Bogota', 15);

INSERT INTO sucursal VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);
INSERT INTO sucursal VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO sucursal VALUES ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

INSERT INTO mecanico VALUES (460, 'Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);
INSERT INTO mecanico VALUES (467, 'Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);
INSERT INTO mecanico VALUES (474, 'Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);
INSERT INTO mecanico VALUES (481, 'Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);
INSERT INTO mecanico VALUES (488, 'Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);
INSERT INTO mecanico VALUES (495, 'Juan', 'Pablo', 'Sanchez', 'R.', NULL, 859000, 23580, 474);
INSERT INTO mecanico VALUES (502, 'Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);
INSERT INTO mecanico VALUES (509, 'Alberto', 'P.', 'Cerda', 'Ramirez', NULL, 559000, 22380, 460);
INSERT INTO mecanico VALUES (516, 'Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);
INSERT INTO mecanico VALUES (523, 'Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Luces', 45000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Desabolladura', 67000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Revision Frenos', 30000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Puerta Trasera', 50000);

INSERT INTO mantencion VALUES (101, 'S01', TO_DATE('12-04-2023','DD-MM-YYYY'), NULL, NULL, 481, 'Reserva');
INSERT INTO mantencion VALUES (102, 'S02', TO_DATE('21-02-2023','DD-MM-YYYY'), TO_DATE('21-02-2023','DD-MM-YYYY'), NULL, 502, 'Entregado');
INSERT INTO mantencion VALUES (103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'), NULL, NULL, 502, 'Anulado');
INSERT INTO mantencion VALUES (104, 'S03', TO_DATE('11-08-2023','DD-MM-YYYY'), TO_DATE('18-08-2023','DD-MM-YYYY'), NULL, 509, 'Entregado');
INSERT INTO mantencion VALUES (105, 'S03', TO_DATE('03-12-2023','DD-MM-YYYY'), NULL, NULL, 509, 'Ingresado');

COMMIT;

-- === Informe 1 ===

SELECT
  cod_mecanico AS "ID MECANICO",
  pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
  sueldo AS "SALARIO",
  monto_impuestos AS "IMPUESTO ACTUAL",
  monto_impuestos * 0.8 AS "IMPUESTO REBAJADO",
  sueldo - (monto_impuestos * 0.8) AS "SUELDO CON REBAJA IMPUESTOS"
FROM mecanico
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

-- === Informe 2 ===

SELECT
  cod_mecanico AS "IDENTIFICADOR",
  pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
  sueldo AS "SALARIO ACTUAL",
  sueldo * 0.05 AS "AJUSTE",
  sueldo * 1.05 AS "SUELDO_REAJUSTADO"
FROM mecanico
WHERE sueldo BETWEEN 600000 AND 900000
   OR cod_supervisor IS NULL
ORDER BY sueldo ASC, pnombre || ' ' || snombre || ' ' || apaterno DESC;

-- ============================================================
-- Script finalizado
-- ============================================================
