-- ============================================================
-- PRY2204 Experiencia 3 Semana 8 - Taller Mecanico Mikes Ltda.
-- Ejecutar conectado como PRY2204_S8 en FREEPDB1
-- ============================================================

-- === Drops manuales ===

DROP TABLE detalle_servicio CASCADE CONSTRAINTS PURGE;
DROP TABLE mantencion CASCADE CONSTRAINTS PURGE;
DROP TABLE automovil CASCADE CONSTRAINTS PURGE;
DROP TABLE premium CASCADE CONSTRAINTS PURGE;
DROP TABLE estandar CASCADE CONSTRAINTS PURGE;
DROP TABLE cliente CASCADE CONSTRAINTS PURGE;
DROP TABLE servicio CASCADE CONSTRAINTS PURGE;
DROP TABLE mecanico CASCADE CONSTRAINTS PURGE;
DROP TABLE sucursal CASCADE CONSTRAINTS PURGE;
DROP TABLE ciudad CASCADE CONSTRAINTS PURGE;
DROP TABLE pais CASCADE CONSTRAINTS PURGE;
DROP TABLE modelo CASCADE CONSTRAINTS PURGE;
DROP TABLE marca CASCADE CONSTRAINTS PURGE;
DROP TABLE tipo_automovil CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE seq_servicio;
DROP SEQUENCE seq_ciudad;

-- === Creacion de tablas ===

CREATE TABLE pais (
  id_pais NUMBER(3) GENERATED BY DEFAULT AS IDENTITY START WITH 9 INCREMENT BY 3,
  nom_pais VARCHAR2(30) NOT NULL
);

CREATE TABLE ciudad (
  id_ciudad NUMBER(3) NOT NULL,
  nom_ciudad VARCHAR2(30) NOT NULL,
  cod_pais NUMBER(3) NOT NULL
);

CREATE TABLE sucursal (
  id_sucursal CHAR(3) NOT NULL,
  nom_sucursal VARCHAR2(20) NOT NULL,
  calle VARCHAR2(20) NOT NULL,
  num_calle NUMBER(4) NOT NULL,
  cod_ciudad NUMBER(3) NOT NULL
);

CREATE TABLE mecanico (
  cod_mecanico NUMBER(5) GENERATED BY DEFAULT AS IDENTITY START WITH 460 INCREMENT BY 7,
  pnombre VARCHAR2(20) NOT NULL,
  snombre VARCHAR2(20) NOT NULL,
  apaterno VARCHAR2(20) NOT NULL,
  amaterno VARCHAR2(20) NOT NULL,
  bono_jefatura NUMBER(10),
  sueldo NUMBER(10) NOT NULL,
  monto_impuestos NUMBER(10) NOT NULL,
  cod_supervisor NUMBER(5)
);

CREATE TABLE cliente (
  rut NUMBER(8) NOT NULL,
  dv CHAR(1) NOT NULL,
  pnombre VARCHAR2(20) NOT NULL,
  snombre VARCHAR2(20),
  apaterno VARCHAR2(20) NOT NULL,
  amaterno VARCHAR2(20) NOT NULL,
  telefono VARCHAR2(12),
  email VARCHAR2(40),
  tipo_cliente CHAR(1) NOT NULL
);

CREATE TABLE automovil (
  patente CHAR(8) NOT NULL,
  annio NUMBER(4) NOT NULL,
  cant_puertas NUMBER(1) NOT NULL,
  km NUMBER(6) NOT NULL,
  color VARCHAR2(30) NOT NULL,
  cod_tipo_auto CHAR(3) NOT NULL,
  cod_modelo NUMBER(5) NOT NULL,
  cod_marca NUMBER(2) NOT NULL,
  cl_rut NUMBER(8) NOT NULL
);

CREATE TABLE marca (
  id_marca NUMBER(2) NOT NULL,
  descripcion VARCHAR2(20) NOT NULL
);

CREATE TABLE modelo (
  id_modelo NUMBER(5) NOT NULL,
  marca_id NUMBER(2) NOT NULL,
  descripcion VARCHAR2(20) NOT NULL
);

CREATE TABLE tipo_automovil (
  id_tipo CHAR(3) NOT NULL,
  descripcion VARCHAR2(20) NOT NULL
);

CREATE TABLE servicio (
  id_servicio NUMBER(3) NOT NULL,
  descripcion VARCHAR2(100) NOT NULL,
  costo NUMBER(7) NOT NULL
);

CREATE TABLE mantencion (
  num_mantencion NUMBER(4) NOT NULL,
  cod_sucursal CHAR(3) NOT NULL,
  fecha_ingreso DATE NOT NULL,
  fecha_salida DATE,
  patente_auto CHAR(8),
  cod_mecanico NUMBER(5) NOT NULL,
  costo_total NUMBER(7) NOT NULL,
  estado VARCHAR2(15)
);

CREATE TABLE detalle_servicio (
  mantencion_num NUMBER(4) NOT NULL,
  cod_servicio NUMBER(3) NOT NULL,
  descuento_serv NUMBER(4,3) NOT NULL,
  cantidad NUMBER(3)
);

CREATE TABLE estandar (
  cl_rut NUMBER(8) NOT NULL,
  puntaje_fidelidad NUMBER(10) NOT NULL
);

CREATE TABLE premium (
  cl_rut NUMBER(8) NOT NULL,
  pesos_clientes NUMBER(10) NOT NULL,
  monto_credito NUMBER(10)
);

-- === Restricciones iniciales ===

ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY (id_pais);
ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY (id_ciudad);
ALTER TABLE sucursal ADD CONSTRAINT sucursal_pk PRIMARY KEY (id_sucursal);
ALTER TABLE mecanico ADD CONSTRAINT mecanico_pk PRIMARY KEY (cod_mecanico);
ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY (rut);
ALTER TABLE automovil ADD CONSTRAINT automovil_pk PRIMARY KEY (patente);
ALTER TABLE servicio ADD CONSTRAINT servicio_pk PRIMARY KEY (id_servicio);
ALTER TABLE mantencion ADD CONSTRAINT mantencion_pk PRIMARY KEY (num_mantencion);
ALTER TABLE detalle_servicio ADD CONSTRAINT detalle_servicio_pk PRIMARY KEY (mantencion_num, cod_servicio);
ALTER TABLE marca ADD CONSTRAINT marca_pk PRIMARY KEY (id_marca);
ALTER TABLE modelo ADD CONSTRAINT modelo_pk PRIMARY KEY (id_modelo, marca_id);
ALTER TABLE tipo_automovil ADD CONSTRAINT tipo_automovil_pk PRIMARY KEY (id_tipo);
ALTER TABLE estandar ADD CONSTRAINT estandar_pk PRIMARY KEY (cl_rut);
ALTER TABLE premium ADD CONSTRAINT premium_pk PRIMARY KEY (cl_rut);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_fk_pais
FOREIGN KEY (cod_pais) REFERENCES pais (id_pais);

ALTER TABLE sucursal ADD CONSTRAINT sucursal_fk_ciudad
FOREIGN KEY (cod_ciudad) REFERENCES ciudad (id_ciudad);

ALTER TABLE mecanico ADD CONSTRAINT mecanico_fk_mecanico
FOREIGN KEY (cod_supervisor) REFERENCES mecanico (cod_mecanico);

ALTER TABLE modelo ADD CONSTRAINT modelo_fk_marca
FOREIGN KEY (marca_id) REFERENCES marca (id_marca);

ALTER TABLE automovil ADD CONSTRAINT automovil_fk_cliente
FOREIGN KEY (cl_rut) REFERENCES cliente (rut);

ALTER TABLE automovil ADD CONSTRAINT automovil_fk_modelo
FOREIGN KEY (cod_modelo, cod_marca) REFERENCES modelo (id_modelo, marca_id);

ALTER TABLE automovil ADD CONSTRAINT automovil_fk_tipo
FOREIGN KEY (cod_tipo_auto) REFERENCES tipo_automovil (id_tipo);

ALTER TABLE estandar ADD CONSTRAINT estandar_fk_cliente
FOREIGN KEY (cl_rut) REFERENCES cliente (rut);

ALTER TABLE premium ADD CONSTRAINT premium_fk_cliente
FOREIGN KEY (cl_rut) REFERENCES cliente (rut);

ALTER TABLE mantencion ADD CONSTRAINT mant_fk_sucursal
FOREIGN KEY (cod_sucursal) REFERENCES sucursal (id_sucursal);

ALTER TABLE mantencion ADD CONSTRAINT mant_fk_automovil
FOREIGN KEY (patente_auto) REFERENCES automovil (patente);

ALTER TABLE mantencion ADD CONSTRAINT mant_fk_mecanico
FOREIGN KEY (cod_mecanico) REFERENCES mecanico (cod_mecanico);

ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_mantencion
FOREIGN KEY (mantencion_num) REFERENCES mantencion (num_mantencion);

ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_servicio
FOREIGN KEY (cod_servicio) REFERENCES servicio (id_servicio);

-- === Caso 2: modificaciones del modelo ===

ALTER TABLE mantencion DROP COLUMN costo_total;

ALTER TABLE detalle_servicio DROP CONSTRAINT det_serv_fk_mantencion;
ALTER TABLE mantencion DROP CONSTRAINT mantencion_pk;

ALTER TABLE mantencion ADD CONSTRAINT mantencion_pk
PRIMARY KEY (num_mantencion, cod_sucursal);

ALTER TABLE detalle_servicio ADD cod_sucursal CHAR(3);
ALTER TABLE detalle_servicio MODIFY cod_sucursal NOT NULL;

ALTER TABLE detalle_servicio ADD CONSTRAINT det_serv_fk_mantencion
FOREIGN KEY (mantencion_num, cod_sucursal)
REFERENCES mantencion (num_mantencion, cod_sucursal);

ALTER TABLE cliente ADD CONSTRAINT un_cliente_email UNIQUE (email);
ALTER TABLE cliente ADD CONSTRAINT ck_cliente_dv CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));
ALTER TABLE cliente ADD CONSTRAINT ck_cliente_tipo CHECK (tipo_cliente IN ('E','P'));
ALTER TABLE mecanico ADD CONSTRAINT ck_mecanico_sueldo CHECK (sueldo >= 510000);
ALTER TABLE mantencion ADD CONSTRAINT ck_mantencion_estado CHECK (estado IN ('Reserva','Ingresado','Entregado','Anulado'));

-- === Secuencias solicitadas ===

CREATE SEQUENCE seq_servicio START WITH 400 INCREMENT BY 2;
CREATE SEQUENCE seq_ciudad START WITH 165 INCREMENT BY 5;

-- === Poblamiento de datos ===

INSERT INTO pais (id_pais, nom_pais) VALUES (9, 'Chile');
INSERT INTO pais (id_pais, nom_pais) VALUES (12, 'Peru');
INSERT INTO pais (id_pais, nom_pais) VALUES (15, 'Colombia');

INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Bogota', 15);

INSERT INTO sucursal VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);
INSERT INTO sucursal VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO sucursal VALUES ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

INSERT INTO mecanico VALUES (460, 'Jorge', 'Pablo', 'Soto', 'Sierpe', 5400000, 2759000, 223580, NULL);
INSERT INTO mecanico VALUES (467, 'Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);
INSERT INTO mecanico VALUES (474, 'Sandra', 'Josefa', 'Letelier', 'S.', 0, 659000, 22358, 460);
INSERT INTO mecanico VALUES (481, 'Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);
INSERT INTO mecanico VALUES (488, 'Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);
INSERT INTO mecanico VALUES (495, 'Juan', 'Pablo', 'Sanchez', 'R.', NULL, 859000, 23580, 474);
INSERT INTO mecanico VALUES (502, 'Carlos', 'Felipe', 'Soto', 'J.', 0, 597000, 23580, 474);
INSERT INTO mecanico VALUES (509, 'Alberto', 'P.', 'Cerda', 'Ramirez', NULL, 559000, 22380, 460);
INSERT INTO mecanico VALUES (516, 'Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);
INSERT INTO mecanico VALUES (523, 'Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Luces', 45000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Desabolladura', 67000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Revision Frenos', 30000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Puerta Trasera', 50000);

INSERT INTO mantencion VALUES (101, 'S01', TO_DATE('12-04-2023','DD-MM-YYYY'), NULL, NULL, 481, 'Reserva');
INSERT INTO mantencion VALUES (102, 'S02', TO_DATE('21-02-2023','DD-MM-YYYY'), TO_DATE('21-02-2023','DD-MM-YYYY'), NULL, 502, 'Entregado');
INSERT INTO mantencion VALUES (103, 'S02', TO_DATE('09-10-2023','DD-MM-YYYY'), NULL, NULL, 502, 'Anulado');
INSERT INTO mantencion VALUES (104, 'S03', TO_DATE('11-08-2023','DD-MM-YYYY'), TO_DATE('18-08-2023','DD-MM-YYYY'), NULL, 509, 'Entregado');
INSERT INTO mantencion VALUES (105, 'S03', TO_DATE('03-12-2023','DD-MM-YYYY'), NULL, NULL, 509, 'Ingresado');

COMMIT;

-- === Informe 1 ===

SELECT
  cod_mecanico AS "ID MECANICO",
  pnombre || ' ' || apaterno AS "NOMBRE MECANICO",
  sueldo AS "SALARIO",
  monto_impuestos AS "IMPUESTO ACTUAL",
  monto_impuestos * 0.8 AS "IMPUESTO REBAJADO",
  sueldo - (monto_impuestos * 0.8) AS "SUELDO CON REBAJA IMPUESTOS"
FROM mecanico
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY monto_impuestos DESC, apaterno ASC;

-- === Informe 2 ===

SELECT
  cod_mecanico AS "IDENTIFICADOR",
  pnombre || ' ' || snombre || ' ' || apaterno AS "MECANICO",
  sueldo AS "SALARIO ACTUAL",
  sueldo * 0.05 AS "AJUSTE",
  sueldo * 1.05 AS "SUELDO_REAJUSTADO"
FROM mecanico
WHERE sueldo BETWEEN 600000 AND 900000
   OR cod_supervisor IS NULL
ORDER BY sueldo ASC, pnombre || ' ' || snombre || ' ' || apaterno DESC;

-- ============================================================
-- Script finalizado
-- ============================================================
